name: floability-env
channels:
  - conda-forge
dependencies:
  - python
  - ndcctools
  - pyyaml
  - requests
  - pip
  - pytest
  - nbformat
  - jupyter_client
  - python-magic  # for MIME type guessing
  - tqdm          # progress bars for streaming
  - aiohttp       # optional async HTTP client
  - fsspec
  - boto3         # AWS S3 support
  - pip:
      - pelicanfs
