[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "floability"
version = "0.2.1"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "pyyaml",
  "requests",
  "tqdm",
  "nbformat",
  "pelicanfs",
]

[project.urls]
Documentation = "https://floability.readthedocs.io/"
Repository = "https://github.com/floability/floability-cli"

[project.scripts]
floability = "floability.cli:main"

[tool.isort]
profile = "black"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.setuptools.package-data]
floability = [
    "bootstrap_templates/*.ipynb",
    "bootstrap_templates/*.yml",
]
